### ISSUE TITLE
bCNC in requrements.txt?

### ISSUE THREAD

**Issue by Harvie** [N-ihad/YT-audio-text-mood-recognizer#1]
are you sure you want to include bCNC in requrements.txt?

This affects both of these repos:

https://github.com/N-ihad/gradient-descent
https://github.com/N-ihad/YT-audio-text-mood-recognizer

**Comment by N-ihad** [comment]
yup, apologies, updated requirements.txt. Is issue solved?

**Comment by Harvie** [comment]
There was no issue, i've just randomly noticed it :-D

**Comment by N-ihad** [comment]
Lol hahahah, have a good day

**Comment by N-ihad** [comment]
Lol hahahah, have a good day and thanks
